-- MySQL Script generated by MySQL Workbench
-- Tue Dec  7 13:12:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dashboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dashboard` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dashboard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_dashboard_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_dashboard_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`service_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`service_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service_instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`service_instance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`service_instance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `end_point` VARCHAR(255) NULL,
  `service_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `service_type_id`),
  INDEX `fk_service_instance_service_type1_idx` (`service_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_instance_service_type1`
    FOREIGN KEY (`service_type_id`)
    REFERENCES `mydb`.`service_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`task` ;

CREATE TABLE IF NOT EXISTS `mydb`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`data_stream_dashboard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`data_stream_dashboard` ;

CREATE TABLE IF NOT EXISTS `mydb`.`data_stream_dashboard` (
  `dashboard_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`dashboard_id`, `task_id`),
  INDEX `fk_data_stream_dashboard_task1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_data_stream_dashboard_dashboard1`
    FOREIGN KEY (`dashboard_id`)
    REFERENCES `mydb`.`dashboard` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_stream_dashboard_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `mydb`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`data_stream_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`data_stream_service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`data_stream_service` (
  `service_instance_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`service_instance_id`, `task_id`),
  INDEX `fk_data_stream_service_task1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_data_stream_service_service_instance1`
    FOREIGN KEY (`service_instance_id`)
    REFERENCES `mydb`.`service_instance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_stream_service_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `mydb`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`source` ;

CREATE TABLE IF NOT EXISTS `mydb`.`source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NULL,
  `api_key` VARCHAR(45) NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`id`, `task_id`),
  INDEX `fk_source_task1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_source_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `mydb`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`scraper_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`scraper_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`scraper_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `repo` VARCHAR(45) NULL,
  `source_id` INT NOT NULL,
  PRIMARY KEY (`id`, `source_id`),
  INDEX `fk_scraper_type_source1_idx` (`source_id` ASC) VISIBLE,
  CONSTRAINT `fk_scraper_type_source1`
    FOREIGN KEY (`source_id`)
    REFERENCES `mydb`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`scraper_instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`scraper_instance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`scraper_instance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `end_point` VARCHAR(45) NULL,
  `task_id` INT NOT NULL,
  `scraper_type_id` INT NOT NULL,
  `scraper_instance_id` INT NOT NULL,
  PRIMARY KEY (`id`, `task_id`, `scraper_type_id`, `scraper_instance_id`),
  INDEX `fk_scraper_instance_task1_idx` (`task_id` ASC) VISIBLE,
  INDEX `fk_scraper_instance_scraper_type1_idx` (`scraper_type_id` ASC) VISIBLE,
  INDEX `fk_scraper_instance_scraper_instance1_idx` (`scraper_instance_id` ASC) VISIBLE,
  CONSTRAINT `fk_scraper_instance_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `mydb`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scraper_instance_scraper_type1`
    FOREIGN KEY (`scraper_type_id`)
    REFERENCES `mydb`.`scraper_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scraper_instance_scraper_instance1`
    FOREIGN KEY (`scraper_instance_id`)
    REFERENCES `mydb`.`scraper_instance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`message` ;

CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` TEXT NULL,
  `scraper_instance_id` INT NOT NULL,
  PRIMARY KEY (`id`, `scraper_instance_id`),
  INDEX `fk_message_scraper_instance1_idx` (`scraper_instance_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_scraper_instance1`
    FOREIGN KEY (`scraper_instance_id`)
    REFERENCES `mydb`.`scraper_instance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`metadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`metadata` ;

CREATE TABLE IF NOT EXISTS `mydb`.`metadata` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NULL,
  `value` TEXT NULL,
  `message_id` INT NOT NULL,
  PRIMARY KEY (`id`, `message_id`),
  INDEX `fk_metadata_message1_idx` (`message_id` ASC) VISIBLE,
  CONSTRAINT `fk_metadata_message1`
    FOREIGN KEY (`message_id`)
    REFERENCES `mydb`.`message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

--------------------------------------------------------
-- Data for table `mydb`.`user`
--------------------------------------------------------

START TRANSACTION;

USE `mydb`;

INSERT INTO `mydb`.`user` (`id`, `name`, `email`, `password`) VALUES (DEFAULT, 'ervin', 'e@gmail.com', 'passw123');
INSERT INTO `mydb`.`user` (`id`, `name`, `email`, `password`) VALUES (DEFAULT, 'andrey', 'a@gmail.com', 'passw321');

COMMIT;

-------------------------------------------------------
-- Data for table `mydb`.`task`
-------------------------------------------------------

START TRANSACTION;

USE `mydb`;

INSERT INTO `mydb`.`task` (`id`, `data`) VALUES (DEFAULT, 'KPI');
INSERT INTO `mydb`.`task` (`id`, `data`) VALUES (DEFAULT, 'Monobank');

COMMIT;

-------------------------------------------------------
-- Data for table `mydb`.`source`
-------------------------------------------------------

START TRANSACTION;

USE `mydb`;

INSERT INTO `mydb`.`source` (`id`, `url`, `api_key`, `task_id`) VALUES (DEFAULT, 'https://university.ua', 'AZdsdadWEqweWQEQWEQds', DEFAULT);
INSERT INTO `mydb`.`source` (`id`, `url`, `api_key`, `task_id`) VALUES (DEFAULT, 'https://bank.ua', 'AZdsdEwerwweWQEQWEQds', DEFAULT);

COMMIT;

